port: 8080
storage:
  home: '/tmp/duke/pix8_data/me'
  private: '/tmp/duke/pix8_data/private'
  items: '/tmp/duke/pix8_data/items'
  dats: '/tmp/duke/pix8_data/dats'
  wiki: '/tmp/duke/pix8_data/wiki'
  youtubes: '/tmp/duke/pix8_data/youtubes'
ggif_app: ''

ffmpeg: ''
ffprobe: ''

windows:
  index:
    openDevTools: true
    file: "electron.html"
    maximize: true
    BrowserWindow:
      icon: "logo.ico"
      frame: false
      show: false
      titleBarStyle: "hiddenInset"
      width: 1800
      height: 300
      useContentSize: true
      title: "Pix8"
      webPreferences:
        plugins: true
        blinkFeatures: "OverlayScrollbars"
